/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.io.PrintStream;

public class LinterTest {
    @Test public void testLinterEmpty() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/empty.js");

        assertEquals("", outContent.toString());
    }

    @Test public void testLinterNoErrors() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/noerrors.js");

        assertEquals("", outContent.toString());
    }

    @Test public void testLinterOneError() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/oneerror.js");

        assertEquals("Line 2: Missing semicolon.\n", outContent.toString());
    }

    @Test public void testLinterFewErrors() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/fewerrors.js");

        assertEquals("Line 2: Missing semicolon.\nLine 4: Missing semicolon.\nLine 5: Missing semicolon.\n", outContent.toString());
    }

    @Test public void testLinterManyErrors() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/manyerrors.js");

        assertEquals("Line 1: Missing semicolon.\nLine 2: Missing semicolon.\nLine 3: Missing semicolon.\nLine 4: Missing semicolon.\nLine 5: Missing semicolon.\nLine 6: Missing semicolon.\n", outContent.toString());
    }

    @Test public void testLinterEmptyLines() {
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Linter classUnderTest = new Linter();
        classUnderTest.linter("src/main/resources/emptylines.js");

        assertEquals("", outContent.toString());
    }
}