/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Linter {
    public static void main(String[] args) {
        if (args.length > 0) {
            linter(args[0]);
        }
    }

    public static void linter(String filePath) {
        int lineCount = 1;
        try {
            Scanner sc = new Scanner(new File(filePath));
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                if (!line.equals("") && !line.endsWith("{") && !line.endsWith("}") && !line.contains("if") && !line.contains("else") && !line.endsWith(";")) {
                    System.out.println(String.format("Line %d: Missing semicolon.", lineCount));
                }
                lineCount++;
            }
        } catch (FileNotFoundException e){
            System.out.println("File not found");
            System.out.println(e);
        }
    }
}
