/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollsOnce() {
        int rolls[] = Library.roll(4);
        assertEquals(4, rolls.length);
    }

    @Test public void testRollsTwoDifferent() {
        int rollsOne[] = Library.roll(3);
        int rollsTwo[] = Library.roll(5);
        assertNotEquals(rollsOne.length, rollsTwo.length);
    }

    @Test public void testContainsDuplicatesTrue() {
        assertTrue(Library.containsDuplicates(new int[]{1,2,4,3,4}));
    }

    @Test public void testContainsDuplicatesFalse() {
        assertFalse(Library.containsDuplicates(new int[]{1,2,3,4}));
    }

    @Test public void testCalculateAverage() {
        assertEquals(2.5f, Library.calculateAverage(new int[]{1,2,3,4}), 0.0f);
    }

    @Test public void testLowestAverage() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        assertEquals(57.0f, Library.lowestAverage(weeklyMonthTemperatures), 0.0f);
    }
}
