console.log("This is missing a semicolon")
console.log("This is missing a semicolon")
console.log("This is missing a semicolon")
console.log("This is missing a semicolon")
console.log("This is missing a semicolon")
console.log("This is missing a semicolon")
